apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose -f docker-compose.yml convert
    kompose.version: 1.26.1 (a9d05d509)
  creationTimestamp: null
  labels:
    io.kompose.service: phpldapadmin
  name: phpldapadmin
spec:
  ports:
    - name: "8085"
      port: 8085
      targetPort: 80
  type: LoadBalancer
  selector:
    io.kompose.service: phpldapadmin
status:
  loadBalancer: {}
