apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose -f docker-compose.yml convert
    kompose.version: 1.26.1 (a9d05d509)
  creationTimestamp: null
  labels:
    io.kompose.service: sia-session-ms
  name: sia-session-ms
spec:
  replicas: 3
  selector:
    matchLabels:
      io.kompose.service: sia-session-ms
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose -f docker-compose.yml convert
        kompose.version: 1.26.1 (a9d05d509)
      creationTimestamp: null
      labels:
        io.kompose.service: sia-session-ms
    spec:
      containers:
        - image: ycuervob/sia_session:gcp8
          name: sia-session-ms
          ports:
            - containerPort: 3000
          resources: {}
      restartPolicy: Always
status: {}
