apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose -f docker-compose.yml convert
    kompose.version: 1.26.1 (a9d05d509)
  creationTimestamp: null
  labels:
    io.kompose.service: sia-wa
  name: sia-wa
spec:
  ports:
    - protocol: TCP
      port: 443
      targetPort: 3800
  type: LoadBalancer
  selector:
    io.kompose.service: sia-wa
status:
  loadBalancer: {}
