apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose -f docker-compose.yml convert
    kompose.version: 1.26.1 (a9d05d509)
  creationTimestamp: null
  labels:
    io.kompose.service: sia-interface
  name: sia-interface
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: sia-interface
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose -f docker-compose.yml convert
        kompose.version: 1.26.1 (a9d05d509)
      creationTimestamp: null
      labels:
        io.kompose.service: sia-interface
    spec:
      containers:
        - env:
            - name: API_HOST
              value: "10.112.3.121"
            - name: API_PORT
              value: "3000" 
          image: ycuervob/sia-proxy-interface:latest
          name: sia-interface
          ports:
            - containerPort: 3000
          resources: {}
      restartPolicy: Always
status: {}
