apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose -f docker-compose.yml convert
    kompose.version: 1.26.1 (a9d05d509)
  creationTimestamp: null
  labels:
    io.kompose.service: sia-proxy-ga-mcs
  name: sia-proxy-ga-mcs
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: sia-proxy-ga-mcs
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose -f docker-compose.yml convert
        kompose.version: 1.26.1 (a9d05d509)
      creationTimestamp: null
      labels:
        io.kompose.service: sia-proxy-ga-mcs
    spec:
      containers:
        - image: ycuervob/sia-proxy-ga-mcs:latest
          name: sia-proxy-ga-mcs
          ports:
            - containerPort: 80
          resources: {}
      restartPolicy: Always
status: {}
