apiVersion: apps/v1
kind: HorizontalPodAutoscaler
metadata:
  annotations:
    kompose.cmd: kompose -f docker-compose.yml convert
    kompose.version: 1.26.1 (a9d05d509)
  creationTimestamp: null
  labels:
    io.kompose.service: sia-general-ag
  name: sia-general-ag
spec:
  maxReplicas: 5
  minReplicas: 1
  selector:
    matchLabels:
      io.kompose.service: sia-general-ag
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose -f docker-compose.yml convert
        kompose.version: 1.26.1 (a9d05d509)
      creationTimestamp: null
      labels:
        io.kompose.service: sia-general-ag
    spec:
      containers:
        - image: ycuervob/sia_general_ag:latest
          name: sia-general-ag
          ports:
            - containerPort: 4000
          resources: {}
      restartPolicy: Always
status: {}
