apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose -f docker-compose.yml convert
    kompose.version: 1.26.1 (a9d05d509)
  creationTimestamp: null
  labels:
    io.kompose.service: sia-proxy-wa-mcs
  name: sia-proxy-wa-mcs
spec:
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  selector:
    io.kompose.service: sia-proxy-wa-mcs
status:
  loadBalancer: {}
