apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose -f docker-compose.yml convert
    kompose.version: 1.26.1 (a9d05d509)
  creationTimestamp: null
  labels:
    io.kompose.service: sia-session-ms
  name: sia-session-ms
spec:
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
  selector:
    io.kompose.service: sia-session-ms
status:
  loadBalancer: {}
