apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose -f docker-compose.yml convert
    kompose.version: 1.26.1 (a9d05d509)
  creationTimestamp: null
  labels:
    io.kompose.service: sia-general-ag
  name: sia-general-ag
spec:
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 80
  type: LoadBalancer
  selector:
    io.kompose.service: sia-general-ag
status:
  loadBalancer: {}
