apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose -f docker-compose.yml convert
    kompose.version: 1.26.1 (a9d05d509)
  creationTimestamp: null
  labels:
    io.kompose.service: sia-academica-ag
  name: sia-academica-ag
spec:
  replicas: 3
  selector:
    matchLabels:
      io.kompose.service: sia-academica-ag
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose -f docker-compose.yml convert
        kompose.version: 1.26.1 (a9d05d509)
      creationTimestamp: null
      labels:
        io.kompose.service: sia-academica-ag
    spec:
      containers:
        - image: ycuervob/sia_academica_ag:latest
          name: sia-academica-ag
          ports:
            - containerPort: 80
          resources: {}
      restartPolicy: Always
status: {}
